### ISSUE TITLE
InnerSource Maturity Model?

### ISSUE THREAD

**Issue by brooklynrob** [finos/InnerSource#11]
All, 

I wanted to ask if anyone has developed or come across an inner source maturity model. 

Specifically I am looking for something that could be used to evaluate internal projects across multiple relevant dimensions to assess the degree to which a project is already demonstrating attributes and capabilities needed to effectively "do inner source" (perhaps w/o the project team even having known what inner source is -- e.g., perhaps they already work to a "public" roadmap within the 4 walls of their organization.)

I was thinking (and might argue that) these dimensions might be similar to those that @mindthegab, @copiesofcopies, @pmonks and I used a few years back to build the [FINOS board report and health check rubric](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/93225748/Board+Reporting+and+Program+Health+Checks), but perhaps not. 

Again, use of the model would be the assess projects inner source readiness across 6-8 dimensions, and an associated rubric. 

Thanks,

Rob
rob(at)ttmadvisors(dot)com

**Comment by amaltson** [comment]
Hey @brooklynrob that's a really great question. I personally haven't seen anything in my experience personally. Perhaps this would be a great project for this SIG to work on? We could pool our varied experiences and see if we can create a common maturity model. The model should provide a baseline and guide organizations to build on it for their own use cases.

That rubric might be a good scaffold to build on, but I think we'd need to tailor it. Ideally we have levels of maturity that are encouraging at **any** level, I wouldn't want organizations to feel they have to be at the highest maturity level and feel discouraged when it's challenging to get there. Adoption could be encouraged by having organizations share what level some of their products are at. It'd also provide us insights where the SIG could focus on.

Anywho, love the idea!

**Comment by Ludmila-N** [comment]
There are a few InnerSource maturity models out there. 
This one for example:
https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/a9e136eb57fd927c12ee27827e35cd7215226e53/patterns/2-structured/maturity-model.md

**Comment by mcleo-d** [comment]
Thanks so much @Ludmila-N 🚀 

The InnerSource SIG is meeting **Wednesday, 14 April 2021 - 10am EST / 3pm UK** if you would like to comment on the agenda below and join the call as I'm sure this issue will be raised?

https://github.com/finos/InnerSource/issues/10

cc @finos/innersource-maintainers

**Comment by daniela-g-zheleva-db** [comment]
> There are a few InnerSource maturity models out there.
> This one for example:
> https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/a9e136eb57fd927c12ee27827e35cd7215226e53/patterns/2-structured/maturity-model.md

Thank you for sharing these! Perhaps it would be useful for us to try pilot this (or another maturity model) with our inner source communities within our organisations. By doing this we can provide feedback on the pattern as well as a 'guide' / tips on how others can do the same. 

Just a thought.

**Comment by mcleo-d** [comment]
Hey @daniela-g-zheleva-db - What are your thoughts on making this issue the first [InnerSource GitHub Discussion](Discussions
). Maybe this could be raised in the InnerSource SIG meeting https://github.com/finos/InnerSource/issues/11 ..? 🤔
