### ISSUE TITLE
10 May 2021 - InnerSource SIG Meeting Minutes

### ISSUE THREAD

**Issue by claredillon** [finos/InnerSource#14]
## Date
Mon 10 May 2021 - 11am EST /  4pm UK

## Untracked attendees
- 

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes [Note we need to approve 2 past meeting minutes]
- [x] Quick update on OSR SIG and plans for Open Source in Finance Webinars
- [x] Review Maturity Matrix first draft and discuss
- [x] AOB & Meeting Adjourned

## Decisions Made / Notes
- Minutes from previous meeting to be distributed to mailing list. We will allow 24 hours for comments. Minutes to be approved if no objection.
- Update provided by @grizzwolf on plans for Open Source in Finance events and activites. Agreed that InnerSource would be covered as a topic alongside other themes such as open source thought leadership.
- Open call made for volunteers to speak at future Open Source in Finance meetups and activities. Join Grizz in Slack channel to follow up: https://finos-lf.slack.com/archives/C01SYB503QT
- Speaker for July activities already in the works. 
- Open call also made for any speakers who want to participate in InnerSource Commons community events. 
- A topic was proposed for future consideration by the SIG: how to do InnerSource with third party contractors / vendors. 
- Re. Maturity Matrix: agreed to convene a 2 hour working session with smaller group to create draft for review by SIG and discussion in the next SIG meeting. 
- - Noted that not everyone has access to Slack and shared documents. Agreed that we will communicate meeting events in multiple channels. 

## Action Items
- [x] Clare to distribute minutes from previous meeting to be distributed to SIG mailing list. 
- [x] Clare to send around a Doodle Poll for the best time slot for follow-up working session.
- [ ] SIG to schedule follow up working session before next SIG scheduled meeting.

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=m33975a6a163e1319c07e33a06bd3d1d5
- Meeting number: 127 765 4882
- Join by phone (US Toll): +1-415-655-0003
- Join by phone (UK Toll): +44-20319-88141
- Access Code: 127 765 4882

### Mailing List
Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list.

**Comment by mcleo-d** [comment]
Hi @claredillon 👋 

Please find the questions that were asked in Understanding the InnerSource Checklist with Silona Bonewald, Executive Director of IEEE SA OPEN - https://www.finos.org/hosted-events/2021-05-05-understanding-the-innersource-checklist-isc 

**James McGovern**
Industry analyst firms such as Gartner do not have InnerSource on their radar or any coverage in their research. Are there organizations that have no interest in open source adopting InnerSource that they should look into?

**Cristina Coffey**
Great talk Silona! I have a quick question: How do you encourage and measure the culture change when you first start with InnerSource?

**Reza Alavi**
What steps did you take to ensure the inner source activities have a realistic vision, an articulated shared purpose and a clear defined problems and opportunities?

**Dan**
Please share your guidance within the context of source code tooling, and if there's a prerequisite of extensive (exclusive?) use of GitHub Enterprise, relative to a current state where multiple repos are currently used?

**Ludmila Nitishinskaya**
What is your best tip on getting middle management support?

**Comment by claredillon** [comment]
Adding here a version of the ISC Maturity Matrix that can be used as a starting point for our discussion today: https://drive.google.com/file/d/1MvmaCwcI30MjlTCoPwKYvL7XdFbLBgzb/view?usp=sharing

**Comment by claredillon** [comment]
Hello!

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by grizzwolf** [comment]
Hello - Grizz, FINOS 🥇

**Comment by DanielleAlmeida** [comment]
Hello!!!

**Comment by danizheleva** [comment]
Hello 🌞

**Comment by mcgovern-wipro** [comment]
Hello

**Comment by eminty69** [comment]
Hello !

**Comment by anvacca** [comment]
Hello!
