### ISSUE TITLE
24 May 2021 - InnerSource SIG Meeting Minutes

### ISSUE THREAD

**Issue by claredillon** [finos/InnerSource#15]
## Date
Mon 24 May 2021 - 11am EST / 4pm UK

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [X] Convene & roll call (5mins)
- [X] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [X] Review Meeting Notices (see above)
- [X] Approve past meeting minutes
- [X] Update on Maturity Matrix Working Session
- [x] AOB, Q&A & Adjourn (5mins)

## Notes
Update from Maturity Matrix Working Session:
- 2 hour working session took place on Wed May 19th. 
- Volunteers taking first pass at the project-focused matrix.
- Goal to have doc circulated to the rest of the working session team by Friday 28th
- Next meeting on Wed June 2nd (invite sent).
- Progress will be reported at SIG meeting on Jun 7th.

Ask for what other topics we could focus on in the future:
- Noted that a previous suggestion was to focus on terms of reference for third party vendors working with FS orgs on InnerSource projects. 
- Agreed that would be useful. Noted that there are no references for this to do that are known in the industry. 

Short discussion followed regarding this challenge:
- Context for vendor InnerSource engagements could include staff augmentation, project work or managed service delivery. 
- Some things to work out include: visibility and access guidelines for vendors, sample contract language, incentives, and strategy requirements.
- Agreed not to be considered in maturity matrix conversation, as might over-complicate.

Other areas discussed:
- Having common technology would be useful. 
- Perhaps we should have a representative in the SIG who could play devil’s advocate around regulatory challenges and suggested mitigations. 
- To address any reticence to engage in public forum,  we could engage privately instead of asking to join the general calls, perhaps through interviews and summarize feedback. 
- Ideally we could also identify common blockers or areas of common resistance in organizations. 
- Regarding “open by default” repos - it was noted that “open by default” repos does not equal InnerSource, nor does InnerSource require “open by default” repos.
- Experience shows there are a mix of policies, common terminology will definitely help. 
- Suggestion we could gather and publish data on who is adopting particular policies and how?
- James gave update on discussion between SIG and ISC: ISC uses CC BY SA for materials, we want to make sure that we have process to work effectively in that context. James, other FINOS/LF team members, Clare and Danese are working towards resolution so we can work together effectively.

## Decisions Made
- Topic for next SIG is the report out from the Maturity Matrix work. 
- Agreed we should continue to capture interesting themes for future
- Doc will be distributed before the review call. 
- Noted that we should also be mindful of the tools that we use to most easily collaborate: Not everyone can use every platform and some are easier to use than others. 

## Action Items
- Graham to follow up with Colin from ScottLogic to get status on planned FINOS survey. 
- Clare to share State of InnerSource 2020 survey results.
- Ivan to share some events by Citizens Bank that are promoting Open Innovation.
- James to review as well to see if FINOS can get involved. 

### WebEx info
Meeting link: https://finos.webex.com/finos/j.php?MTID=m33975a6a163e1319c07e33a06bd3d1d5
Meeting number: 127 765 4882
Join by phone (US Toll): +1-415-655-0003
Join by phone (UK Toll): +44-20319-88141
Access Code: 127 765 4882

### Mailing List
Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list.

**Comment by Ivan-Radovanovic** [comment]
hello all

**Comment by daniela-g-zheleva-db** [comment]
Hello

**Comment by godds** [comment]
Hello 👋

**Comment by claredillon** [comment]
Hello everyone! :)

**Comment by RichardWagener365** [comment]
Hi everyone

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by grizzwolf** [comment]
howdy

**Comment by DanielleAlmeida** [comment]
Hello everyone!!
