### ISSUE TITLE
07 Jun 2021 - InnerSource SIG Meeting Minutes

### ISSUE THREAD

**Issue by claredillon** [finos/InnerSource#17]
## Date
Mon 07 Jun 2021 - 11am EST / 4pm UK

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Update on Maturity Matrix Working Session. Details here: https://github.com/finos/InnerSource/discussions/12
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] ...

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=m33975a6a163e1319c07e33a06bd3d1d5
- Meeting number: 127 765 4882
- Join by phone (US Toll): +1-415-655-0003
- Join by phone (UK Toll): +44-20319-88141
- Access Code: 127 765 4882

### Mailing List
Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list.

**Comment by Ivan-Radovanovic** [comment]
hello all

**Comment by amaltson** [comment]
👋

**Comment by godds** [comment]
👋

**Comment by mcleo-d** [comment]
Hi 👋🏻

**Comment by RichardWagener365** [comment]
Hi

**Comment by Ludmila-N** [comment]
hi

**Comment by daniela-g-zheleva-db** [comment]
Hello

**Comment by jgavronsky** [comment]
Jane here
