### ISSUE TITLE
21 Jun 2021 - InnerSource SIG Meeting Minutes

### ISSUE THREAD

**Issue by claredillon** [finos/InnerSource#18]
## Date
Mon 21 Jun 2021 - 11am EST / 4pm UK

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] OSSF Call for Papers - InnerSource SIG Panel Discussion - London, October 4-5 and New York, November 9-10.
  - https://events.linuxfoundation.org/open-source-strategy-forum/
- [x] FINOS State of Open Source in Financial Services Survey 
  - https://linuxfoundation.surveymonkey.com/r/FINOS21
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes
- Clare raised issue related to OSSF events: proposed some talks/panels be submitted from the InnerSource SIG
  - Looking for speakers / volunteers to participate. Please get in touch with Clare / comment here if you would like to be involved or have suggestions for topics / speakers: https://github.com/finos/InnerSource/discussions/21
  - James noted there are two events: one in London (Oct) and one in New York (Nov). Agreed we would plan for both, perhaps repeating content, perhaps not. 
  - Suggestions for topics include: panel on the maturity matrix, panel discussing the pros and cons of InnerSource-first or open source-first approaches, the differences between intent and reality of InnerSource efforts. 
  - Agreed we would continue the conversation asynchronously
- Update on Maturity Matrix:
  - James, Daniela agreed to work with Anthony to merge last set of feedback into the Google doc to produce “close to final” version next week. 
  - It will be distributed to the SIG mailing list for final review once that is done.
  - Call for volunteers to bring into org to test. (Graham volunteered to share it internally)
- What’s next?
  - We touched on what might be the next focus for InnerSource SIG. 
  - Agreed to look at creating examples referenced in the maturity matrics (e.g. example SLA). Do a check-in with the SIG members to see what they would prioritise. 
  - Noted another idea was to look at sample agreement for 3rd party vendors to work on InnerSource.
  - The discussion raised the idea of discussing biggest blockers/challenges once again with the community. 
  - From Daniela: if folks have ideas on future ideas for focus - please put in this discussion: https://github.com/finos/InnerSource/discussions/13
- Other:
  - James has added a link to the survey that is happening. Call to distribute. https://www.research.net/r/NS8XV6W
 

## Decisions Made
- We intend to submit a talk for OSSF London/NY 2021 and OSPOCon London
- Discussion regarding what's next for SIG will continue here: https://github.com/finos/InnerSource/discussions/13
- Next InnerSource SIG meeting scheduled for July 12th! (a week later than the original schedule due to 4th July). Details here: https://github.com/finos/InnerSource/issues/19 

## Action Items
- [ ] Daniela & James to catch up with Anthony to include his feedback in the Maturity Matrix. Doc will be shared with group.

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=m33975a6a163e1319c07e33a06bd3d1d5
- Meeting number: 127 765 4882
- Join by phone (US Toll): +1-415-655-0003
- Join by phone (UK Toll): +44-20319-88141
- Access Code: 127 765 4882

### Mailing List
Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list.

**Comment by claredillon** [comment]
Propose we discuss today the idea of submitting a panel session to the OSSF London (dates Oct 4/5 - CFP closes Jul 11)

**Comment by daniela-g-zheleva-db** [comment]
Hello :)

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by godds** [comment]
Hello 👋

**Comment by claredillon** [comment]
Hello everyone! :)

**Comment by RichardWagener365** [comment]
Hi - Richard from Codethink

**Comment by gyehuda** [comment]
Hello

**Comment by clcoffey** [comment]
Hi

**Comment by DanielleAlmeida** [comment]
Hello!

**Comment by chamindra** [comment]
Hello Chamindra here 👋

**Comment by claredillon** [comment]
Daniel Shaya asked to be added to roll call in WebEx chat!
