### ISSUE TITLE
12 July 2021 - InnerSource SIG Meeting Minutes

### ISSUE THREAD

**Issue by mcleo-d** [finos/InnerSource#19]
## Date
Monday 12 July 2021 - 11am EST / 4pm UK

_// Rescheduled from US public holiday on 5th July_

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Announce Maturity Matrix V0.1
- [x] Discuss formation of maturity matrix sub work-stream and gauge participation 
- [x] Announcement: @daniela-g-zheleva-db departure from InnerSource SIG
- [x] ...
- [x] AOB, Q&A & Adjourn (5mins)

## Meeting minutes

- Update on Maturity Matrix:
  -  @mcleo-d explained that editing the Google Sheet was becoming challenging as we scaled, and so we have proposed to lock the current version of the Matrix. The decision was accepted.
  - @mcleo-d review of steps from @anvacca, agreed by SIG
    1. Let SIG know we are in a frozen state. Provide the read only copy and thank them, let them know the overall plan/timelines.
    2. Once previous step is fine, work with @mcleo-d to create GitHub project (decide where it goes etc) and move data over.
      - One person assigned to do this with support of @mcleo-d.
    3. Once previous step is complete, person to provide a walkthrough to the SIG leads of the new GitHub project that was created.
    4. Formally assign maintainers to maintain repo and do another around of edits to further clean up the documents.
    5. Go through a formal review process with wider group using new tools/process.
    6. publish 1.0.0 if no objections.
  - @mcleo-d explained the current state of InnerSource Commons/Linux Foundation discussions around CCLA. This is currently preventing us from giving concrete timelines on when the matrix can be submitted as a project.
  - Reviewed process of submitting a project proposal when the SIG is ready. Clarified that we need to have maintainers identified before the submission is made. Brief description of maintainers duties - govern the repo, approve PRs, review issues, report back to SIG.
  - The project is proposed to work in a Hub and Spoke model, where the InnerSource SIG is the HUB and we form a sub-working group to focus on the Maturity Matrix (Spoke). 
  - @eminty69, @aaronsearle and @godds expressed interest in the sub-working group

- @danizheleva updated the SIG that she is stepping back from the Co-Lead position, and that this leaves the position open.
  - @mcleo-d proposed the leadership group have a retrospective to review whether to continue with the co-lead model or try something else.
  -  Claryfication that any addition to a named role (i.e. a lead) needs to be decided through a democratic process. This means a nomination and approval from the rest of the SIG. Noted that this is not a formal interview process, and there is no interviews etc.

- Other business discussed: what to do next?
  - @amaltson showed the SIG curated lists of certain technologies/topics, called Awesome Lists (eg. the [macOS Awesome List](https://github.com/iCHAIT/awesome-macOS#readme) or [list of lists](https://github.com/sindresorhus/awesome)) and discussed how we could use it in this SIG or maybe directly in InnerSource Commons
  - @eminty69 mentioned how the Matrix can be expanded to include Open Source.
  - All encouraged to add their thoughts in the following GitHub issue https://github.com/finos/InnerSource/discussions/13 

## Decisions Made
- [x] Matrix version 0.1 is now locked/frozen. It will be circulated round, but no changes will be made until it is submitted to GitHub

## Action Items
- [x] @danizheleva to circulate maturity matix read-only spreadsheet and PDF to SIG distribution list
- [x] @danizheleva to add call to action in GitHub issue and kick off process for nominating a new co-lead
- [ ] @mcleo-d to update on when we can bring the Maturity Matrix into FINOS as a contributing process
- [ ] Leadership team to have a retro on the way we have worked so far

### WebEx info
- Meeting link : https://finos.webex.com/finos/j.php?MTID=m3a6ed8ca517918da899f5a0ee90f8b93
- Meeting number: 127 355 1226
- Join by phone
  - +1-415-655-0003 US Toll
  - +44-20319-88141 UK Toll
  - Access code: 127 355 1226

### Mailing List
Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list

**Comment by amaltson** [comment]
👋

**Comment by daniela-g-zheleva-db** [comment]
Hey everyone

**Comment by RichardWagener365** [comment]
Hi there, Richard from Codethink

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by godds** [comment]
👋

**Comment by jgavronsky** [comment]
Jane here

**Comment by eminty69** [comment]
Hello, I'm Elspeth

**Comment by aaronsearle** [comment]
Hello

**Comment by mcleo-d** [comment]
The latest update and frozen version PDFs for the Maturity Model have been posted to GitHub Discussion for further review and feedback by August 30th 2021 ... https://github.com/finos/InnerSource/discussions/12#discussioncomment-1022570
