### ISSUE TITLE
SIG leadership position open!

### ISSUE THREAD

**Issue by daniela-g-zheleva-db** [finos/InnerSource#22]
A position has recently opened up to join the InnerSource SIG leadership team as the groups co-lead!

This is a really exciting opportunity to work closely with the leadership team and help drive the amazing progress this group is already achieving! 

**Please find the InnerSource SIG Co-Lead role described below ...**
https://github.com/finos/InnerSource/blob/master/docs/open-roles/innersource-sig-co-lead.md

The process requires a nomination, and approval from the rest of the SIG. If you are interested please contact James (@mcleo-d )

The leadership team currently is:

Name | Firm | Role
-- | -- | --
Daniela Zheleva | Deutsche Bank | SIG Lead
Arthur Maltson | Capital One | SIG Co-Lead
Clare Dillon | InnerSource Commons | SIG Secretary
Aaron Searle | Morgan Stanley | SIG Leadership Committee
Anthony Vacca | RBC | SIG Leadership Committee
Danese Cooper | InnerSource Commons | SIG Leadership Committee

**Comment by vmbrasseur** [comment]
Hey there, @mcleo-d. Could you please post a sort of job description for this position so people who'd be nominated can have a better idea of what they might be getting into?

**Comment by amaltson** [comment]
I nominate @eminty69 as a co-lead, she'd be an awesome addition to the leadership team.

**Comment by godds** [comment]
Seconded!

**Comment by amaltson** [comment]
Awesome, confirming @eminty69 as the co-lead!
