### ISSUE TITLE
19 July 2021 - InnerSource SIG Meeting Minutes

### ISSUE THREAD

**Issue by mcleo-d** [finos/InnerSource#25]
## Date
Monday 19 July 2021 - 11am EST / 4pm UK

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Repo cleanup.
- [ ] AOB, Q&A & Adjourn (5mins)

## Meeting minutes
* Still ongoing discussion on how the licensing will work for the Maturity Matrix, @mcleo-d to keep us in the loop.
* Potential collaboration opportunity to collaborate with @copiesofcopies on the forthcoming Open Source Readiness (OSR) SIG.
  * OSR SIG would be looking to make a maturity matrix for organizations on their Open Source adoption and contribution maturity.
  * Potential opportunity to collaborate on defining the difference between [InnerSource and OpenSource per discussion suggestion](https://github.com/finos/InnerSource/discussions/13#discussioncomment-898550).
* Richard pointing out that for organizations to be start contributing in the open there's an 
* @mcleo-d mentioned upcoming OSR meeting...

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- Meeting link: 
- Meeting number: 
- Password:
- Call-in:

### Mailing List
Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list.

**Comment by amaltson** [comment]
👋

**Comment by RichardWagener365** [comment]
Hi

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by mcleo-d** [comment]
FINOS ALL COMMUNITY CALL
**Wednesday July 21, 2021, 10.00am EDT / 3.00pm BST**
[**Register here to join the Zoom call**](https://zoom.us/webinar/register/6016245645034/WN_qNObFDBjR8KLuVzC1tXvlw?__hstc=18943911.2cba9a5eca55736e77e4dcf3e0149ada.1567507898042.1626704633836.1626710538614.546&__hssc=18943911.2.1626710538614&__hsfp=3620222165&hsCtaTracking=84ca6422-6d3a-4370-bc6f-241e96160f85%7Cbd19e4a3-2e95-4b2c-8e1e-698fda8ccf5b)

Join us for our quarterly "All Community Call" where the FINOS team and community will provide updates on what's been happening within the Foundation as well as what's coming up. We're still working on some of the specifics but we'll definitely be covering the topics below.

**Comment by claredillon** [comment]
Checked in with Richard - he can't recall the context of the unfinished minute item above.

**Comment by amaltson** [comment]
The notes look OK, the second last sentence isn't fully filled out though...

**Comment by claredillon** [comment]
Thanks @amaltson - I checked in with Richard - but he can't remember the context - so we'll have to get James to edit that one before signing off.

**Comment by amaltson** [comment]
@mcleo-d is there anything else we need to do to close this issue out? Do we just close it or was there a GitHub Action to run? Thanks!

**Comment by mcleo-d** [comment]
Great reminder @amaltson 🚀 

I have closed this issue and the others that were approved in the last SIG meeting 👍🏻

**Comment by amaltson** [comment]
Thanks @mcleo-d! Can I close these in the future or is this something you need to do? We approved these during the SIG meeting and I’d love to help out 😄
