### ISSUE TITLE
2 August 2021 - InnerSource SIG Meeting Minutes

### ISSUE THREAD

**Issue by mcleo-d** [finos/InnerSource#26]
## Date
Monday 2 August 2021 - 11am EST / 4pm UK

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes - Approval at next meeting #25
- [x] Backlog grooming and prioritisation of InnerSource SIG work - https://github.com/finos/InnerSource/discussions
- [x] InnerSource SIG representation at Open Source Readiness on 4th August at 10am EST / 3pm BST 
  - https://github.com/finos/open-source-readiness/issues 
  - https://www.finos.org/hosted-events/2021-08-04-open-source-readiness-sig-1st-meeting
- [x] InnerSource SIG on FINOS Slack - Review requests and keeping informed.
  - https://finos-lf.slack.com/archives/C01SYB503QT 
- [x] SIG leadership position open! - https://github.com/finos/InnerSource/issues/22
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
- Webex : https://finos.webex.com/finos/j.php?MTID=m33975a6a163e1319c07e33a06bd3d1d5
- Meeting number: 127 765 4882

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 127 765 4882

### Mailing List
Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list.

**Comment by claredillon** [comment]
Hello!

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by aaronsearle** [comment]
Hi

**Comment by eminty69** [comment]
Hello from Elspeth

**Comment by brooklynrob** [comment]
Here.

**Comment by Danese** [comment]
Hello!

**Comment by claredillon** [comment]
Minutes from the meeting (@mcleo-d - perhaps you might add to the issue above - sorry I can't edit it).

# Meeting Notes

- Minutes from 19th July not approved - need to add some final details to unfinished line items.
- OSR kicking off as SIG this week. 
  - James McLeod proposed that we have InnerSource SIG representation on the work for OS Maturity Matrix.
  - We should have someone on Wednesday 4th OSR SIG Meeting. 
  -  Clare volunteered.
- Reviewed next SIG Priorities
  - Reviewed related SIG discussion: https://github.com/finos/InnerSource/discussions/13
  - Suggested that one priority should be infographic about how IS and OSS relate - for reference for OSR SIG. Ask for people to discuss in next SIG meeting. And also ask who can potentially be available to help create. 
  - Clare also suggested it would be good to try and capture the example items from the maturity matrix before we lose the context. 
- Reminder about the status of the Maturity Matrix. PDFs in discussion final. Waiting on LF guidance for CCLAs/licensing to submit into repo. 
- Agreed we would have a regular action to sweep the FINOS #innersource-sign channel to pull discussions into GitHub for maximum accessibility by SIG members. 
- SIG Leadership
  - Noted that the feedback from Arthur is that having a co-lead is very helpful and we do want to continue this practice in the SIG. 
  - Short statement on what we are looking for: It would be great to have diverse representation in the SIG LT across a wide set of criteria - individual diversity (e.g. gender) and organizational diversity (e.g. geography, InnerSource experience, org type). However, most important criteria is a willingness and availability to co-lead. 
- Meeting closed. Next meeting in two weeks time. 

# Action Items
- Clare to follow-up with Richard to get detail from the unfinished minute line from last meeting.
- Clare to attend the OSR SIG meeting on Wednesday and share that we are working on InnerSource/Open Source infographic - how they relate.
- Re. next priorities - Clare to invite owners of suggested next priorities to next meeting to discuss and ask which areas people might be available to help in.
- James to create template issue to review FINOS Slack InnerSource SIG channel to gather any relevant info and bring back to GitHub discussions for maximum accessibility for SIG members.
