### ISSUE TITLE
30 AUG 2021 - InnerSource SIG Meeting Minutes

### ISSUE THREAD

**Issue by claredillon** [finos/InnerSource#31]
## Date
Monday 30 August 2021 - 11am EST / 4pm UK

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
![Screenshot 2021-08-30 at 08 58 55](https://user-images.githubusercontent.com/6029572/131306172-cbc74ff2-7a7a-4cb7-a5ba-6d336a893cea.png)
- [x] Review FINOS Slack InnerSource SIG Channel - https://finos-lf.slack.com/archives/C01SYB503QT
- [ ] Agenda item 1
- [ ] Agenda item 2
- [ ] ...
- [x] AOB, Q&A & Adjourn (5mins)

## Discussion
- Update on InnerSource Slack Channel: no new content in previous 2 weeks.
- Update on InnerSource Maturity Matrix:
  - Waiting for James to return from holidays to get update on process for moving forwards.
  - Noting OSR SIG also creating a maturity matrix. In the future, we should work to agree standard format for maturity matrices and input to InnerSource section of OSR’s maturity matrix. 
- Update on Awesome Style list: 
  - James to also advise on how to publish Awesome style list.
  - Ask for everyone to add their favourite InnerSource resources to the discussion here: https://github.com/finos/InnerSource/discussions/30
  - Feedback from group is to use Markdown
- Update on Case Studies:Two streams of work planned: 
  - Gather light evidence style and list and record the companies that doing IS
  - Create case studies that discuss challenges in more depth, perhaps anonymously.
- Update re OSSF Panel Session:- InnerSource SIG submitting pre-recorded panel session.
- Update from InnerSource Commons:
  - Community Calls that may be of interest to SIG
    - Sep 7th (EU/US time) will feature early InnerSource adopters Georg Grutter from Bosch and Isabel Drost-Fromm from Europace covering lessons learned from their InnerSource journeys. Register here: https://bit.ly/2Uda1jA
    - Sep 21st (EU/APAC time) will feature Matt Cobby from National Australia Bank with Willem Jiang from Huawei InnerSource in the Enterprise Register here: https://bit.ly/3kDNKok
  - CFP is open for the InnerSource Summit - please do consider submitting proposal for 10-15 min talk here: https://bit.ly/2WxLgiR

## Decisions Made
- [ ] Minutes from previous meeting signed off - noting we can't complete the last sentence from 19th July
- [ ] Minutes will be sent to the SIG mailing list in the week after SIG meetings - if there are no objections, they will be approved in the next SIG meeting. 

## Action Items
- [ ] Clare to send out minutes to mailing list
- [ ] All to add their suggestions to Awesome Style discussion here: https://github.com/finos/InnerSource/discussions/30
- [ ] James to update on process for submitting work into GitHub in next SIG meeting. 
- [ ] All to consider submitting to InnerSource Summit CFP here: https://bit.ly/2WxLgiR
- [ ] James to close previous meetings now that minutes have been signed off

### WebEx info
- Webex : https://finos.webex.com/finos/j.php?MTID=m33975a6a163e1319c07e33a06bd3d1d5
- Meeting number: 127 765 4882

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 127 765 4882

### Mailing List
Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list.

**Comment by claredillon** [comment]
Hello everyone!

**Comment by Julia-Ritter** [comment]
Julia here! // FINOS

**Comment by vmbrasseur** [comment]
VMBrasseur, Wipro

**Comment by RichardWagener365** [comment]
Hi

**Comment by godds** [comment]
👋

**Comment by clcoffey** [comment]
hello

**Comment by Danese** [comment]
Howdy <3 Thanks for coming everyone.
