### ISSUE TITLE
11 OCT 2021 - InnerSource SIG Meeting Minutes

### ISSUE THREAD

**Issue by claredillon** [finos/InnerSource#34]
## Date
Monday, 11 Oct 2021 - 11am EST / 4pm UK

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Review FINOS Slack InnerSource SIG Channel - https://finos-lf.slack.com/archives/C01SYB503QT
- [x] Contributing InnerSource SIG maturity matrix to FINOS - https://github.com/finos/InnerSource/discussions/12#discussioncomment-1022570 **&&** https://github.com/finos/InnerSource/discussions/29
- [x] OSSF London Panel Retrospective. Just how awesome were we? 😄 
  -  Are there any leads we need to act upon?
- [x] OSSF NYC Panel Planning. How can we expand on the success of London? 🤔 
- [x] @amaltson Hacktoberfest - I was wondering if you'd be open to having the InnerSource SIG (and maybe FINOS in general) participate in Hacktoberfest? I was hoping to add our repo, and if we can create it, the matrix repo, as participants in Hacktoberfest. All that's needed is to add the #hacktoberfest topic to the repo and it qualifies. I'm organizing an event at work to participate in Hacktoberfest and would love to devote focused time to making forward progress on some of what we've talked about :slightly_smiling_face: 
- [x] AOB, Q&A & Adjourn (5mins)

### Maturity Matrix

- Update from James to say we can contribute under CC BY SA. 
- Decided that we will contribute into the InnerSource SIG repo.
- Decided we will use doc format, with sections for each table cell (not reproduce table of current pdf).
- Decided we will use Markdown and Docusaurus.
- Action - Clare to enquire whether we can get help from ISC in conversion. 
- Note that Open Source Maturity Matrix (from OSR group) also now intending to contribute under CC BY SA.

### OSSF

- Great feedback from our panel sessio - format (mixed recording and live) worked really well.
- There was a proposal that we do something similar for OSSF New York event - However, unfortunately, word from the OSSF New York event organizers is that they are prioritizing in -person talks. Instead, we plan to do a sequel to the panel for a future FINOS virtual event.

### Discussion re Hacktoberfest
- Re. InnerSource Matrix: Decided that we will contribute into the InnerSource SIG repo. Decided we will use doc format, with sections for each table cell (not reproduce table of current pdf). Decided we will use Markdown and Docusaurus.
- Agreed it would be great in principle - but that it is not a priority for this year for the InnerSource SIG because we are not set up due to timing and the requirement for contextual knowledge to help with the maturity matrix. 
- However, if anyone in the group would like to take on getting registered and working under the Hacktoberfest banner - that would also be welcome.
- There was a note that we should have a mechanism to track future planned work items - like a plan to get involved with more notice next year. 

### Other

- **SIG Co-lead Position still open** - accepting nominations here: https://github.com/finos/InnerSource/issues/22. We hope to close this at the next SIG Meeting

- Reminder from InnerSource Commons to get signed up for the **InnerSource Summit 2021** - all virtual - running November 17th & 18th. There are a number of Financial Services themed talks with **Elspeth Minty (Morgan Stanley), Gil Yehuda (US Bank), Jesus Alonso Gutiérrez (Santander), and Matt Cobby (National Australia Bank)** all talking. And lots to learn from other industry insights too! Visit https://bit.ly/3BuCa65 to register. 

Reminder the cadence of the InnerSource SIG meetings has changed to once every 4 weeks to allow for time for other contributions. **Next meeting is November 8th** - and you can add any agenda items to the GitHub issue here: https://github.com/finos/InnerSource/issues/38 

## Decisions Made
- Re. Hacktoberfest: Agreed it would be great in principle - but that it is not a priority for this year for the InnerSource SIG because we are not set up due to timing and the requirement for contextual knowledge to help with the maturity matrix. However, if anyone in the group would like to take on getting registered and working under the Hacktoberfest banner - that would also be welcome.

## Action Items
- [x] Clare to enquire whether we can get help from ISC in conversion. 
- [x] Arthur to set up our repo as part of Hacktoberfest
- [ ] There was a note that we should have a mechanism to track future planned work items - like a plan to get involved with more notice next year. James to advise on how we should do this.
- [ ] Anyone interested in SIG Co-lead role - nominate yourself under https://github.com/finos/InnerSource/issues/22

### WebEx info
- Webex : https://finos.webex.com/finos/j.php?MTID=m33975a6a163e1319c07e33a06bd3d1d5
- Meeting number: 127 765 4882

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 127 765 4882

### Mailing List
Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list.

**Comment by amaltson** [comment]
Approved some time ago 😉
