### ISSUE TITLE
08 NOV 2021 - InnerSource SIG Meeting Minutes

### ISSUE THREAD

**Issue by claredillon** [finos/InnerSource#38]
## Date
Monday, 08 Nov 2021 - 11am EST / 4pm UK

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Review FINOS Slack InnerSource SIG Channel - https://finos-lf.slack.com/archives/C01SYB503QT
- [x] Vote on @eminty69 as InnerSource Co-Lead with @amaltson - https://github.com/finos/InnerSource/issues/22#issuecomment-946749824
- [x] Review #39
- [x] Raising PR for Maturity Matrix contribution https://github.com/finos/InnerSource/discussions/12#discussioncomment-1022570
- [ ] PR reviews needed before @amaltson merges ...
  - #41 
  - #42 
  - #43 
  - #44

Each pull request needs members of the InnerSource SIG community to hit the `Files Changed` tab, review the changes and give feedback by hitting the green `Review Changes` button. This is open to everyone! 😁 

![Screenshot 2021-11-03 at 11 24 32](https://user-images.githubusercontent.com/6029572/140052089-7b1aa426-10ab-4478-9964-026f0269b388.png)

- [ ] AOB, Q&A & Adjourn (5mins)

## Minutes

Group voted Elspeth Minty in as InnerSource SIG Co-Lead. Congratulations Elspeth!

Discussion re license for InnerSource SIG repo:
- Confirmed we are applying CC-BY-SA to the Maturity Matrix
- Recommended that we look at reuse.software, who have a good tutorial on applying the licenses https://reuse.software

Maturity Matrix Update:
- File added to repo in Excel
- Arthur will export as CSV and run Pandoc next. 
- Some ISC volunteers are available to help tidy up.
- Limited people have ability to merge, Elspeth as Co-Lead will be able to merge in the future.

Review/demo of pull requests:
- Arthur discussed some work that he wants to do to ensure that doc formatting is easy and well set up for the future.
- Graham reviewed 3 pull requests already and will review the DevContainer as soon as he will install Docker. 

Other ideas to kickstart before the InnerSource SIG Anniversary:
- Case studies
- Example InnerSource Vendor Agreement 
- Find the other challenges to address for 2022

## Decisions Made
- Elspeth voted in as SIG Co-lead!

## Action Items
- [ ] Arthur to add Prettier and format all Markdown Docs
- [ ] Arthur to add a pipeline GitHub Action
- [ ] Arthur to look at DevContainer - Make it easier for people that want to contribute to make changes without having to set anything up
- [ ] Graham to review DevContainter
- [ ] Clare to start issue on case study template
- [ ] Clare to start issues on requirements for Vendor agreement
- [ ] James to give an overview of OSSF New York highlights at the next meeting. 

### WebEx info
- Webex : https://finos.webex.com/finos/j.php?MTID=m33975a6a163e1319c07e33a06bd3d1d5
- Meeting number: 127 765 4882

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 127 765 4882

### Mailing List
Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list.

**Comment by godds** [comment]
Hello

**Comment by claredillon** [comment]
Hello

**Comment by amaltson** [comment]
Hello :wave:

**Comment by vmbrasseur** [comment]
Howdy. VMB from Wipro.

**Comment by eminty69** [comment]
Hello :-)

**Comment by clcoffey** [comment]
Hello

**Comment by jgavronsky** [comment]
Jane Gavronsky / FINOS

**Comment by claredillon** [comment]
Hello to everyone

**Comment by amaltson** [comment]
Approved some time ago 😉
