### ISSUE TITLE
13 DEC 2021 - InnerSource SIG Meeting Minutes

### ISSUE THREAD

**Issue by claredillon** [finos/InnerSource#46]
## Date
Monday, 13 Dec 2021 - 11am EST / 4pm UK

## Untracked attendees
- Peter Smulovics, Morgan Stanley

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Review FINOS Slack InnerSource SIG Channel - https://finos-lf.slack.com/archives/C01SYB503QT
- [x] James to give overview of OSSF New York highlights
- [x] Maturity Matrix Update
- [ ] Discussion on priorities for 2022 for InnerSource SIG
- [ ] ...
- [ ] AOB, Q&A & Adjourn (5mins)

## Notes from Meeting

- The meeting minutes from previous SIG meeting were approved 
- Formal congratulations for Elspeth for being voted as co-lead with Arthur
- James to give the highlights of OSSF New York
  - InnerSource was represented there but not the IS SIG with the travel restrictions between US and Canada and UK (e.g. CapitalOne)
  - Where people were talking about maturity for OS, IS was present in some shape or form. 
  - IS appeared as InnerSource as well as open source internally
  - People saying that they want to get more involved ISC or find a community that is relevant. James managed to promote the FINOS SIG  in this context
  - IS is often described as the first step towards open source
  - Maturity matrix is very valuable in that sense because it will show a company where they are in their path towards open source

- The State of Open Source in Financial services is available for download and the data is available as open source: 
  - https://www.finos.org/state-of-open-source-in-financial-services-2021
  - Youtube link: https://www.youtube.com/watch?v=pwknmDB3cgg
  - Notes: 
    - need for more clarity on the similarities and differences between InnerSource and open source. 
    - IS is driven from the executive level 

- Maturity Matrix Update
  - No dependency on Arthur’s work
  - Arthur researched Pendoc to see if it could work. Nothing definitive yet but it would be good to rule it out before moving on to manual transfer.
  - The Markdown File was created here: https://github.com/finos/InnerSource/tree/master/docs/maturity-matrix
  - The Matrix will be represented in a document style 

- Discussion of focus for 2022
  - Make this community more collaborative and encourage more regular contributions
  - Help make clear the similarities and differences between open source and InnerSource and educate.
  - Case study template - where and how people are using InnerSource - aim to document where people are doing IS and the reasons they are doing it 
  - Help people when they are using contractors for IS 

- Feb 2nd, 2022 - FINOS Community call inviting projects in SIGs to represent themselves.
- How do we get to the OSR emailing list so we don’t miss out on the meetings
  - Send an email to: subscribe+osr@finos.org to subscribe
  - If that doesn’t work send an email to help@finos.org

- State of InnerSource Survey at InnerSource Commons
    - Please complete and share : https://www.surveymonkey.com/r/SOIS2021 
    
- The next FINOS SIG meeting will be on the 10th January 2022

Happy Christmas everyone! 

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [x] Update and close issue re leadership 
- [ ] Clare to add issue re Case Study template
- [ ] ...

### WebEx info
- Webex : https://finos.webex.com/finos/j.php?MTID=m33975a6a163e1319c07e33a06bd3d1d5
- Meeting number: 127 765 4882

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 127 765 4882

### Mailing List
Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list.

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by claredillon** [comment]
Hello there!

**Comment by godds** [comment]
Hello

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by amaltson** [comment]
👋

**Comment by clcoffey** [comment]
Hello

**Comment by chamindra** [comment]
Hi 👋

**Comment by amaltson** [comment]
Approved some time ago 😉
