### ISSUE TITLE
10 JAN 2022 - InnerSource SIG Meeting Minutes

### ISSUE THREAD

**Issue by claredillon** [finos/InnerSource#48]
## Date
Monday 10th Jan 2022 - 11am EST / 4pm UK

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Review FINOS Slack InnerSource SIG Channel - https://finos-lf.slack.com/archives/C01SYB503QT
- [ ] Agenda item 1
- [ ] Agenda item 2
- [ ] ...
- [ ] AOB, Q&A & Adjourn (5mins)

## Minutes

Review of Maturity Matrix
- New PRs merged, README and Org Maturity Matrix now there. 
- Decision made to merge and iterate.
- Arthur has used Prettier (open source project) to make sure that all documents look consistent. 
- Feedback Included
  - Where possible, we should add examples of what good looks like.
  - Note again - not all orgs will be aiming for far right of maturity matrix, but what’s best for their needs and context.
  - For those wanting to get started with InnerSource, [InnerSource Commons](HTTP://www.innersourcecommons.org)  is a good place to start. Check out their Learning Path (intro training), Books and Patterns (best practices).
  - Agreed: Folder & file structure: README plus two pages for org / project.

FINOS community meeting - 2nd of February - 4pm UK
- Agreed we will offer update for Community Meeting
- Good platform to introducing the work that has been done on the Maturity Matrix 
- Arthur/Elspeth/Clare to talk for 2-3 mins

Some next areas for SIG to work on:
- Examples of licensing/SLAs
- Case Studies

Next Meeting
- On Feb 14th
- For Agenda: Discuss Legal scenarios in next meeting - scoping; Gathering case studies - evidence of who is doing what and how are we going to record that

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- Webex : https://finos.webex.com/finos/j.php?MTID=m33975a6a163e1319c07e33a06bd3d1d5
- Meeting number: 127 765 4882

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 127 765 4882

### Mailing List
Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list.

**Comment by godds** [comment]
👋

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by claredillon** [comment]
hello!

**Comment by amaltson** [comment]
Hi

**Comment by clcoffey** [comment]
Hello

**Comment by aaronsearle** [comment]
Hello all.

**Comment by mcleo-d** [comment]
Say hello here 👍🏻

**Comment by lspiro-Tick42** [comment]
Leslie Spiro / Glue42

**Comment by mcleo-d** [comment]
@robbkeayes - Please say hello in the comments below ...

**Comment by chamindra** [comment]
Hello there 👋

**Comment by mcleo-d** [comment]
InnerSource Patterns - @robbkeayes

https://innersourcecommons.org/learn/books/innersource-patterns/

**Comment by amaltson** [comment]
Approved some time ago 😉
