### ISSUE TITLE
Announce InnerSource SIG and First Scheduled Meeting to FINOS Community

### ISSUE THREAD

**Issue by mcleo-d** [finos/InnerSource#5]
### Description
As we get closer to the first InnerSource SIG meeting, it would be great to send out an InnerSource SIG announcement to announce@finos.org that includes the date and time, plus a link to the first meeting agenda.

This item can also be found in FINOS Community InnerSource Contribution [#84](https://github.com/finos/community/issues/84)

## FINOS Announcement
- [ ] Work with FINOS marketing to send out announcement to announce@finos.org , checkout announcement template at https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/83034172/Contribute
- [ ] Notify @mcleo-d, @toshaellison and @grizzwolf once the announcement has been sent out (FINOS infra)

**Comment by mcleo-d** [comment]
@claredillon, @amaltson and @daniela-g-zheleva-db

It would be good to get the FINOS announce email done now **10 Mar 2021 - InnerSource SIG Meeting Minutes** #6 has been scheduled and can be socialised wider in FINOS.

Let me know the help and support needed to move forward?

James.

**Comment by amaltson** [comment]
@claredillon is this something you and @Danese want to run with? I'm not well versed in advertising, you two would have a wealth of experience 😀

**Comment by claredillon** [comment]
Sounds good @amaltson - I'll work through the process with James today!

**Comment by claredillon** [comment]
Email sent to announce@finos.org!
