### ISSUE TITLE
14 MAR 2022 - InnerSource SIG Meeting Minutes

### ISSUE THREAD

**Issue by claredillon** [finos/InnerSource#57]
## Date
Monday 14th Mar 2022 - 11am EST / 3pm UK

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Review FINOS Slack InnerSource SIG Channel - https://finos-lf.slack.com/archives/C01SYB503QT
- [x] Maturity Matrix
- [x] Discussion on themes of interest for potential InnerSource SIG events/panels.
- [ ] ...
- [x] AOB, Q&A & Adjourn (5mins)

## Notes
- We now have the maturity matrics and awesome list in the docs folder
- Skeleton build for Docusaurus to render a basic website (microsite) so that we can show off the matrix in a digestible way
- Docusaurus has been updated to V2. by James
  - Netlifly - used as a standard for microsites for FINOS
  - Decision made to stick to the standard
  - Graham Odds- offered to spend some time to make it pretty
- We got flagged for non-inclusive language keyword
  - Once the PRs are merged then we can rename the branch to solve this
- Maturity matrix
  - Clare Dillon to review attributions based on the original contributors from ISC
- Leadership team meeting to discuss the idea of public events  to broaden awareness around InnerSource SIG
  - Clare to schedule
- Arthur - will be moderator for the CapitalOne panel about InnerSource - fruitful to share it Details from [Capital One's earlier talk](https://www.finos.org/blog/capital-ones-innersource-journey-roderick-randolph-and-arthur-maltson)
- Call for submissions [Linux Foundation Open Source summit](https://events.linuxfoundation.org/open-source-summit-north-america/program/cfp/#suggested-topics) - Proposing FINOS panel - advertise the maturity matrix  
  - Clare to submit virtual panel proposal with Elspeth, Arthur, Graham and James
- Next area of focus: Clare proposes looking at Individual skills vs Org skills in the context of the Maturity Matrix 
  - Attributes of a successful InnerSource maintainer and contributor.)
  - Empathy - the main word to focus on from both parts
  - Is there anything specific that is InnerSource that would not be open source? Slight difference - in the volunteer vs employee (level of empathy) 
  - Company dynamics and politics and how prioritizations happen 
  - The assumption that people understand open source practices and tools
  - Transfer pricing - transferring IP between country boundaries resulting in transfer taxes - system blocker 
  - ACTION: Start the discussion on the skills - Graham to start and share first draft / starting point
- Other business
  - Integrating FINOS sig and project repos with the Open source security foundation from the Linux foundation 
  - Different training available

## Decisions Made
- [ ] Keep 4 week cadence for SIG meetings

## Action Items
- [ ] Clare to arrange a Leadership team meeting to discuss the option of having different format SIG Meetings
- [ ] Graham to start a discussion on skills by sharing a first draft of some docs which may be relevant. 
- [x] Clare to submit the proposal for the LF OSS Summit in Austin for a FINOS panel.

### WebEx info
- Webex : https://finos.webex.com/finos/j.php?MTID=m33975a6a163e1319c07e33a06bd3d1d5
- Meeting number: 127 765 4882

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 127 765 4882

### Mailing List
Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list.

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by clcoffey** [comment]
Hello

**Comment by godds** [comment]
Hi

**Comment by eminty69** [comment]
hello

**Comment by amaltson** [comment]
Approved and closing
