### ISSUE TITLE
11 APR 2022 - InnerSource SIG Meeting Minutes

### ISSUE THREAD

**Issue by claredillon** [finos/InnerSource#59]
## Date
Monday 11th Apr 2022 - 11am EST / 4pm UK

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Review FINOS Slack InnerSource SIG Channel - https://finos-lf.slack.com/archives/C01SYB503QT
- [ ] Progress on work items
- [ ] Discuss change in SIG format to include more outreach events.
- [ ] Discuss [InnerSource Commons State Of InnerSource Survey 2021](https://innersourcecommons.org/learn/research/state-of-innersource-survey-2021/).
- [ ] ...
- [ ] AOB, Q&A & Adjourn (5mins)

## Minutes
- Reviewing [InnerSource Commons State Of InnerSource Survey 2021](https://innersourcecommons.org/learn/research/state-of-innersource-survey-2021/)
  - Went through @claredillon's presentation summarizing the survey.
  - Interesting to see the changing reasons behind why invest in InnerSource, breaking down silos and improving happiness at work. Maturing to open source falling lower down the scale.
  - Biggest barrier is middle management buy-in and lack of time.
    - Only a minority at 13% get all the time they need to contribute to InnerSource.
  - Discussion about advertising or lack thereof for InnerSource projects, maybe an opportunity to add to Maturity Matrix.
  - InnerSource Commons participation is shifting from grass roots to top down as a strategic importance.
    - Recognition still very much lacking.
  - Team readiness - ready to review changes as they come, but when contribution changes requires difficult conversations, less team readiness on that.
  - Project readiness - documentation still a top level concern.

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- Webex : https://finos.webex.com/finos/j.php?MTID=m33975a6a163e1319c07e33a06bd3d1d5
- Meeting number: 127 765 4882

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 127 765 4882

### Mailing List
Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list.

**Comment by vmbrasseur** [comment]
👋

**Comment by clcoffey** [comment]
hello

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by amaltson** [comment]
👋
