### ISSUE TITLE
10 Mar 2021 - InnerSource SIG Meeting Minutes

### ISSUE THREAD

**Issue by claredillon** [finos/InnerSource#6]
## Date
Wednesday, 10 Mar 2021 - 10am EST / 3pm UK

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Introduce the mission and goals of the SIG
- [x] Share priority themes as identified by LT
- [x] Get feedback and input from wider group
- [x] AOB, Q&A & Adjourn (5mins)

## Points of Note / Decisions Made
- Shared the topics the LT had proposed:
    - Common policies / guidelines / principles around InnerSource 
    - How to measure InnerSource success and value?
    - Identify patterns
        - Cultural / behavioural patterns
        - Project patterns 
        - Operational / organisational patterns
    - How can we best advocate for InnerSource?
    - What supporting code/tools do we have that could be open sourced?
    - Feedback for tools vendors
- Feedback from the group
    - Some InnerSource use cases discussed e.g. InnerSource being used to share code with clients.
    - Danese shared ISC community example of Daimler using InnerSource to co-create code with vendors.
    - Discussion around motivations to InnerSource 
        - Interest in hearing more about different InnerSource policies e.g. Open First policy 
        - Interest in discussing value propositions, problems, pain points. 
        - Interest In how to get started and how to scale InnerSource as topics
        - Interest in specific guidelines e.g. 
            - when is the size of the PR too big?
            - Interest in sharing common components (utilities, dev docs)
            - Interest in exploring how to get business functions engaged, some experience from some members to share here. 
    - Shared good starting points:
        - CI/CD, central services.
        - Re-architecture that impacts multiple sites. 
        - Localizations per market
        - Culture hacking (non-code projects)
- Next meeting to have a voting option for which topic to cover. 
- Next meeting to be either set up in 2 weeks or 4 weeks time, SIG LT to get input. 

## Action Items
- @claredillon to set up next SIG Meeting

### WebEx info
- **Webex Link**
  - https://finos.webex.com/finos/j.php?MTID=m55bc361e677ce7e35540fc9714802f87
- **Access Code**
  - 127 618 9803
- **Join by Phone**
  - +1-415-655-0003 US Toll
  - +44-20319-88141 UK Toll
- **Global Numbers**
  - https://finos.webex.com/finos/globalcallin.php?MTID=ma10d45d95f5627e8d6e87d5b269167cf

### Mailing List
Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list.

**Comment by 11306** [comment]
Hello all 
may I attend that meeting

**Comment by claredillon** [comment]
> Hello all
> may I attend that meeting Ivan Radovanovic [ivan.radovanovic@yahooo.com](mailto:ivan.radovanovic@yahooo.com)

We'd be delighted if you can attend, Ivan. Details for the call are included above - and you might like to send a mail to  innersource+subscribe@finos.org to join the mailing list for future notifications!

**Comment by claredillon** [comment]
Hello!!

**Comment by daniela-g-zheleva-db** [comment]
Hello everyone!

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by EnricoTrentin** [comment]
Hello, everyone

**Comment by grizzwolf** [comment]
Howdy

**Comment by amaltson** [comment]
👋

**Comment by lspiro-Tick42** [comment]
Here

**Comment by roderickrandolph** [comment]
Hello 👋🏽

**Comment by cr20ro20** [comment]
Craig Rowe

**Comment by clcoffey** [comment]
Hello

**Comment by jomarsilvazup** [comment]
Hello!

**Comment by Ivan-Radovanovic** [comment]
hello from Boston MA 
beautiful sunny day outside and sending sun to everyone

**Comment by PhillipStephes** [comment]
Hello from Seattle.

**Comment by agitana** [comment]
hi from sunny NYC

**Comment by anvacca** [comment]
Hi!

**Comment by Ivan-Radovanovic** [comment]
2 week

**Comment by amaltson** [comment]
@mcleo-d is there anything else to do with this issue now that the meeting is done? I assume @claredillon needs to post the meeting notes and then it can be closed? Thanks!

**Comment by claredillon** [comment]
@amaltson it's on the agenda for next meeting to approve minutes and close this issue.
