### ISSUE TITLE
13 JUN 2022 - InnerSource SIG Meeting Minutes

### ISSUE THREAD

**Issue by claredillon** [finos/InnerSource#65]
## Date
Monday, 13th June 2022 - 11am EST / 4pm UK

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Review FINOS Slack InnerSource SIG Channel - https://finos-lf.slack.com/archives/C01SYB503QT
- [x] [Call to Register for June 21st Event](https://www.finos.org/hosted-events/2022-06-21-finos-innersource-sig-panel-event)
- [x] Update on Activities
- [x] InnerSource License Working Group
- [x] [Open Source in Finance Forum in London](https://events.linuxfoundation.org/open-source-finance-forum-london) on July 13th 2022 - @mcleo-d 
- [x] AOB, Q&A & Adjourn (5mins)

## Open Source in Finance Forum London, July 13th 2022

Register below for the FINOS [Open Source in Finance Forum](https://events.linuxfoundation.org/open-source-finance-forum-london/) in London on July 13th 2022 👾💥

Open Source in Finance Forum is the only conference dedicated to driving collaboration and innovation in financial services through open source software and standards.

We bring together experts across financial services, technology, and open source to engage our community in stimulating and thought-provoking conversations about how to best (and safely) leverage open source software to solve industry challenges.

FINOS members employees are eligible to receive complimentary registration as part of their company’s membership. Please email [osff@finos.org](mailto:osff@finos.org) to request the Finos Member access code.

Register and find out more 👉🏻 https://events.linuxfoundation.org/open-source-finance-forum-london/

<a href="https://events.linuxfoundation.org/open-source-finance-forum-london/"><img src="https://user-images.githubusercontent.com/6029572/171230930-a68f99a3-ac8d-4738-8054-87af2d45b544.png" width="85%" /></a>

### WebEx info
- Webex : https://finos.webex.com/finos/j.php?MTID=m33975a6a163e1319c07e33a06bd3d1d5
- Meeting number: 127 765 4882

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 127 765 4882

### Mailing List
Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list.

**Comment by claredillon** [comment]
Hello everyone!

**Comment by chamindra** [comment]
Hello All!

**Comment by amaltson** [comment]
👋

**Comment by clcoffey** [comment]
Hello

**Comment by clcoffey** [comment]
Notes for the Minutes:
- Panel Session planned on the 21st of June: https://www.finos.org/hosted-events/2022-06-21-finos-innersource-sig-panel-event?mc_cid=e8ec8cff0f&mc_eid=73110f0184
- Graham created the microsite for FINOS InnerSource SIG 🎉
- InnerSource License Working Group - to meet over the summer and explore the implications of licenses. People from InnerSource Commons will be asked if they want to join the working group, also information from InnerSource Commons will be shared related to this context. 
**ASK**: Recommend people in the legal field that might be interested in joining the group.

- Open Source in Finance Forum (July 13th) update by James. Register and find out more 👉🏻 https://events.linuxfoundation.org/open-source-finance-forum-london/
- CFP now open for New York Open Source in Finance Forum (Dec, 8) https://events.linuxfoundation.org/open-source-finance-forum-new-york/

Other business discussed
- ACTION: Include on the agenda for the next meeting: Decide on an URL (Sub Domain) for the InnerSource SIG Microsite
- Save the Date: 8-9th September 2022 - InnerSource Commons is planning the first in-person gathering in Dublin.
