### ISSUE TITLE
`innersource.finos.org` registered and pointed to `InnerSource` `Netlify` `Docusaurus` build

### ISSUE THREAD

**Issue by mcleo-d** [finos/InnerSource#66]
@maoo and @TheJuanAndOnly99 👋🏻 

Can the subdomain `innersource.finos.org` be registered and pointed to the production version of the `InnerSource` `Netlify` `Docusaurus` build.

Many thanks,

James.

Related to #62

**Comment by maoo** [comment]
Hi @amaltson - yes, Netlify should automatically deploy; could you please access [innersource.finos.org](http://innersource.finos.org/) and confirm? TY!

**Comment by amaltson** [comment]
It's working perfectly! Looks like the SSL cert is working and valid too. Thank you so much, this is fantastic!
