### ISSUE TITLE
07 NOV 2022 - InnerSource License Working Group Meeting

### ISSUE THREAD

**Issue by chamindra** [finos/InnerSource#72]
## Date
_Monday_ 07 NOV 2022 - _11:00am_ EST / _4:00pm_ UK

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Introduction of Inner Source License Working Group Goals and Key Outcomes
- [x] Working Group Participant/Contributor intros 
- [x] Key Roles and Contribution Areas needed
- [x] Discuss and Agree on working group operating/collaboration model 
- [x] Discussion minutes from FINOS Banks Only OSPO Roundtable - https://github.com/finos/open-source-readiness/issues/65
- [x] Discuss Key Next steps
- [x] Schedule Next Meeting
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [x] We decided to create a license generator similar to Creative Commons for Inner Source
- [x] We decided to meet every two weeks at the same time. Next meeting will be on the 21st
- [x] We decided to use git issues for our collaboration

## Action Items
- [x] Publish slides as PDF for reference - Chamindra / James
- [x] Look into license generator code options - Chamindra / Peter
- [ ] Share any prior work on inner source licenses - All
- [x] Create initial issues in GitHub to start the discussion prior to next meeting - Chamindra

## Minutes
- We went through the goals and objectives of the inner source license working group (as captured in PDF)
- We discussed the key outcomes from the group (as per decisions above)
- We discussed contribution opportunities
   - A request was made to share prior work on inner source licenses (obfuscated if needed)
   - Peter and Chamindra are interested in contributing to the license generator code
   - We can get some legal review from FinOS/Linux foundation provided sufficient notice is provided
- It was mentioned we could potentially use the Creative Commons code for the license generator as it is open source
   - we are expect to have less license options
- We discussed the collaboration model and contribution opportunities
   - Bi-weekly meeting for working group at the same time
   - Discussions in the form of GitHub issues

## Meeting Presentation as PDF
- [InnerSource SIG Licenses Working Group 7th November 2022.pdf](https://github.com/finos/InnerSource/files/9954255/Inner.Source.SIG_.Licenses.WG.-.7-Nov-22.pdf)

### WebEx info
- Webex : https://finos.webex.com/finos/j.php?MTID=maecde604b8ce6039f78dbdd63be43d61
- Meeting number: 2550 534 4397

Join by phone
+1-415-655-0003 US Toll
+44-20319-88141 UK Toll

### Mailing List
Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list.

**Comment by BrittanyIstenes** [comment]
I will be travelling on the 7th to GitHub Universe, but would want to be in the next session.  At least one person from Fannie Mae could be represented.

**Comment by AvijitBiswas-socgen** [comment]
Happy to join the meeting. 
Regards,
Avi 
[avijit.biswas@socgen.com]

**Comment by chamindra** [comment]
> I will be travelling on the 7th to GitHub Universe, but would want to be in the next session. At least one person from Fannie Mae could be represented. [brittany_istenes@fanniemae.com](mailto:brittany_istenes@fanniemae.com)

Thanks for your interest. We will look to move the meeting to accommodate more participants.

**Comment by mcleo-d** [comment]
Hi @BrittanyIstenes - Can you recommend a person from Fannie Mae to take your place so we can run the meeting on 7th November as planned? Many thanks!

**Comment by mcleo-d** [comment]
Hello 🐹 ⚡

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by gahuja** [comment]
Girish Ahuja: SMBC

**Comment by chamindra** [comment]
Hi 👋

**Comment by mcleo-d** [comment]
Please find attached the `Inner Source SIG_ Licenses WG - 7-Nov-22.pdf` as presented in the meeting by @chamindra.

- [InnerSource SIG Licenses Working Group 7th November 2022.pdf](https://github.com/finos/InnerSource/files/9954255/Inner.Source.SIG_.Licenses.WG.-.7-Nov-22.pdf)
