### ISSUE TITLE
21 NOV 2022 - InnerSource License Working Group Meeting #2

### ISSUE THREAD

**Issue by chamindra** [finos/InnerSource#76]
## Date
_Monday_ 21 NOV 2022 - _11:00am_ EST / _4:00pm_ UK

## Untracked attendees
- Katrina Novakovic, Citi

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Discuss gathering prior work in Inner Source License and CLAs (ref: https://github.com/finos/InnerSource/issues/75)
- [x] Discuss approach to analysis
- [x] Discuss licence generator options
- [x] AOB, Q&A & Adjourn (5mins)

## Actions
- Create a base MD file to capture the inner source license clauses - Chamindra
- Reach-out to organisations on organisational licenses example - Katrina, Richard, Chamindra
- Share the inner source commons video on the need for a common inner source license definition - Chamindra
- Get back on decision on migrating the working group to zoom based meetings - James
- Add everyone in this working group to the FinOS inner source DL - James

## Key Decisions
- We will collaborate on the Inner Source license classes on an MD file on the Inner Source repository
- We will add everyone in the working group to the inner source SIG DL for more interactive collaboration

## Minutes
- We briefly recapped on the goals of the group and the minutes/actions of the first kickoff meting
- We discussed prior work in this areas and shared the inner source commons reference https://patterns.innersourcecommons.org/p/innersource-license
- There was a call out to gather more examples of inner source licenses that might exist at organisation level
- The group will reach out to different sources to get example of organisations inner source licenses (Katrina, Richard, Chamindra)
  - We will also reachout to inner source commons
- The license generator code of Creative Commons was shared by Peter 
- Rob asked if there are good examples of inner source license in organisations. 
- We discussed the premise is that an common inner source license definition will simplify and make inner source more accessible in organizations
  - Chamindra to share the video presentation at inner source commons that articulates this
- Everyone at the meeting shared that mostly they do not presently have an inner source license of their own to share but is interested in a common license definition
- Chamindra will create a MD file so we can collaborate on the license clauses
- All attendees will be added to the inner source distribution list
- It was discussed if we can move to Zoom from WebEx
- It was discussed that we can add everyone to the inner source DL for a more interactive discussion till the next call

### WebEx info
- Webex : https://finos.webex.com/finos/j.php?MTID=maecde604b8ce6039f78dbdd63be43d61
- Meeting number: 2550 534 4397

Join by phone
+1-415-655-0003 US Toll
+44-20319-88141 UK Toll

### Mailing List
Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list.

**Comment by BrittanyIstenes** [comment]
I am unable to attend todays session due to overlapping meetings within my regular workflow.  Looking forward to seeing folks in NYC.

**Comment by chamindra** [comment]
Hi All 👋

**Comment by brooklynrob** [comment]
Rob Underwood, GS

**Comment by RichardWagener365** [comment]
Richard Wagener, Codethink - Hi

**Comment by mcleo-d** [comment]
Hello 🍔 🍟
