### ISSUE TITLE
05 DEC 2022 - InnerSource License Working Group Meeting #3

### ISSUE THREAD

**Issue by chamindra** [finos/InnerSource#80]
## Date
_Monday_ 05 Dec 2022 - _11:00am_ EST / _4:00pm_ UK

## Untracked attendees
- Katrina Novakovic, Citi
- Schlomo Schapiro 

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes https://github.com/finos/InnerSource/issues/76
- [ ] Review FINOS Slack InnerSource SIG Channel - https://finos-lf.slack.com/archives/C01SYB503QT
- [ ] Review Actions from last meeting
  - MD file creation - Chamindra - https://github.com/chamindra/InnerSource/blob/master/docs/licenses/clauses.md
  - Results from reaching out to different orgs on org licenses / contracts  - Katrina, Peter, Chamindra
  - Adding of everyone in last meeting and those interested in OSPO to DL - James
- [ ] Review base MD file created to capture License rights / clauses
- [ ] Have an initial look into the CC license generator code https://github.com/creativecommons/chooser
- [ ] AOB, Q&A & Adjourn (5mins)

## Action Items
- [ ] Tidyup clauses.md with feedback during meeting - Chamindra
- [ ] Open issue on clauses.md to get further offline feedback - Chamindra
- [ ] Provide input on clauses - All
- [ ] Schedule more detailed session on DB Inner Source license - Katrina

## Minutes
- We reviewed the high level clauses of the inner source license
   - Feedback was provided by the working group and this was committed to the .md file in short form
   - Further tidy up will be done by Chamindra on the clauses and feedback
   - It will be subsequently published as an issue for further discussion
- Katrina had reached out to Schlomo who had be instrumental in publishing the Deutsche Bahn (DB) Inner Source license to inner source commons. DB is a license for a German multinational in the transport sector
- Schlomo provided the background of the DB Inner Source license however we ran out of time to go through the clauses in detail. 
  - DB is an example of an active inner source license that is being used, examples of which was requested at the last meeting
  - We will look to schedule a subsequent session to go through the detail clauses and background for them.
- Key items discussed/added around clauses
  - Consider boundary conditions on mergers and aquasitions
  - It is not just source code that needs to be considered, but also documentation, CI/CD and issues around product
  - There might be additional data seperation walls (if data is in code) that need to be considered
  - Identifying an Authorizing body in the license to handle policy and exceptions might be valuable
  - Export restrictions on territories (e.g. encryption and data as code)
  - Potential of having a copyleft clause in the inner source license as DB, which them mentioned encouraged sharing due to attribution
  - Certain clauses might not be enforcable by law, however this is the case for any software license (e.g. GPL, Apache)
  - Having a license for inner source can reuse existing compliance processes that exist for adopting open source and COTs licenses
  - There is still a discussion if we need to create a base license (building off the DB work) or a license generator

## Decisions
- No decisions were taken at this meeting

### Zoom Details

- https://zoom.us/j/94949043746?pwd=WnBFQjhpUnBjMWE0OUhqUGhhb0ZOdz09
- **Meeting ID:** 949 4904 3746
- **Passcode:** 067897

### Join by phone
Find your local number: https://zoom.us/u/adJnH9JOiY

### Mailing List
Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list.

**Comment by godds** [comment]
👋

**Comment by amaltson** [comment]
👋

**Comment by RichardWagener365** [comment]
Hi

**Comment by psmulovics** [comment]
Hi!
