### ISSUE TITLE
19 DEC 2022 - InnerSource SIG License Working Group Meeting #4

### ISSUE THREAD

**Issue by chamindra** [finos/InnerSource#84]
## Date

_Monday_ 19 DEC 2022 - _11:00AM_ EST / _4:00pm_ UK

## Untracked attendees

- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices

- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [ ] Convene & roll call (5mins)
- [ ] Display
      [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf)
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes (https://github.com/finos/InnerSource/issues/80)
- [ ] Review Tidied up Clauses.md (https://github.com/chamindra/InnerSource/blob/master/docs/licenses/clauses.md)
- [ ] Review approach for Deep Dive on Inner Source License, Clauses, Background and Lessons Learned
- [ ] Ideitify projects and owners to run Deep Dives
- [ ] AOB, Q&A & Adjourn (5mins)

## Minutes
- We reviewed and approved the past two meeting minutes of the Inner Source License WG
- We reviewed the tided up clauses.md from the past meeting discussions
- Feedback to the clauses.md can be provided either as a pull request to https://github.com/chamindra/InnerSource/blob/master/docs/licenses/clauses.md or comments can be provided on the issue https://github.com/finos/InnerSource/issues/85
- The approach on the deeper dive was discussed
   - we will reach out to inner source projects like backstage to get their input on clauses
   - Chamindra will come up with a base questionnaire for the basis of the discussion
- Scheduling discussion with Inner Source projects
   - We will schedule the next deep dive with DB for 9th Jan 2023
   - We will look to join a discussion with on project Backstage.io to do a deep dive with them
   - Citi is going to do some deep dives with their internal inner source projects. An approach need to be sought on sharing this information without violating any policies/regulations/sensativities
- next meeting is scheduled for 9th Jan after the new year

## Decisions Made
No new decisions were made

## Action Items
- Create initial questionnaire for deep dive with inner source projects to understand their license clauses - Chamindra
- Schedule next deep dive with DB for the 9th 2023 - Katrina
- Schedule deep dive with backstage.io - James/Peter
- Work on deep dive with Citi Inner Source projects - Katrina/Chamindra

### Zoom Details

- https://zoom.us/j/94949043746?pwd=WnBFQjhpUnBjMWE0OUhqUGhhb0ZOdz09
- **Meeting ID:** 949 4904 3746
- **Passcode:** 067897

### Join by phone
Find your local number: https://zoom.us/u/adJnH9JOiY

### Mailing List

Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG
mailing list.

**Comment by chamindra** [comment]
👋

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by jaz4th** [comment]
Hello :)

**Comment by psmulovics** [comment]
hello!

**Comment by katnovakovic** [comment]
Hi everyone :)
