### ISSUE TITLE
09 JAN 2023 - InnerSource SIG License Working Group Meeting #5

### ISSUE THREAD

**Issue by chamindra** [finos/InnerSource#86]
## Date

_Monday_ 09 JAN 2023 - _11:00am_ EST / _4:00pm_ UK

## Untracked attendees

- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices

- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [ ] Convene & roll call (5mins)
- [ ] Display
      [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf)
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Review Inner Source License deep dive [questionnaire](https://docs.google.com/forms/d/e/1FAIpQLSczj6ll2Puu4Ldm20gy-GrvDAUk1A7dkXMU4TOsaQh23UinHA/viewform?vc=0&c=0&w=1&flr=0&usp=mail_form_link) (can be provided as a doc file if access is blocked)
- [ ] Deep dive with Deutsche Bahn on their inner source project
- [ ] Review any contributions to the clauses.md can be provided either as a pull request to https://github.com/chamindra/InnerSource/blob/master/docs/licenses/clauses.md or comments can be provided on the issue https://github.com/finos/InnerSource/issues/85
- [ ] AOB, Q&A & Adjourn (5mins)

## Minutes

- We reviewed the questionnaire for the deep dive and initiated it's use with Deutsche Bahn
- It was mentioned that many other known companies also have inner source licenses, but they are not published like Deutsche Bahn and publicly available
   - The representation from DB felt a shared inner source license would be of value
- Key Insight from the discussion at the SIG meeting
  - Inner Source license has brand value in the organization
  - It is part of the gradual process of professionalizing inner source 
  - Included in the license protection is application code, Devops config, data, documentation
  - The inner source license is used only within the organization and not with vendors
  - Licenses are well know mechanism in Open Source and a natural extension for Inner Source
  - License is a tool for the expected behaviour but enforcement depends on a lot of factors including local laws
     - For example certain warranty terms are not compatible with  German law
     - The license a more valuable communication tool than it is a hard legal instrument
  - In particular Tax law is a key are of focus with transfer pricing as a result of inner source
  - The owner of the code can be sometimes blurryP
  - The use of copy left is less strong than in the open source world
  - contributors get recognised directly by GIT contribution tracking
  - Internal career recognition, copyleft and an element of fun are drivers for inner source
  - The Inner source licenses is provided with no-warrenty but that is not the best instrument for getting support
  - The governance body for the inner source license is informally the OSPO
 
## Action Items

- [x] Setup next Inner Source license WG meeting - Chamindra
- [x] Tidy up clauses.MD with variations from DB - Chamindra
- [ ] Look running Inner source questionnaire at Citi - Chamindra / Katrina
- [ ] Seek other organisations that have an inner source license for deep dive similar to DB - All
- [ ] Follow up on backstage inner source discussion - James / Andrew?

### Zoom Details

- https://zoom.us/j/94949043746?pwd=WnBFQjhpUnBjMWE0OUhqUGhhb0ZOdz09
- **Meeting ID:** 949 4904 3746
- **Passcode:** 067897

### Join by phone
Find your local number: https://zoom.us/u/adJnH9JOiY

### Mailing List

Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG
mailing list.

**Comment by chamindra** [comment]
> Can you please provide the link to the Questionnaire? We may have missed it

Hi Brittany, thanks for the question. I was planning to review/refine the Questionnaire at working group meeting on Monday as the first thing we do, however I have a draft I am working on here https://docs.google.com/forms/d/e/1FAIpQLSczj6ll2Puu4Ldm20gy-GrvDAUk1A7dkXMU4TOsaQh23UinHA/viewform?vc=0&c=0&w=1&flr=0&usp=mail_form_link

Feel free to send me some comments for improvement in advance

**Comment by BrittanyIstenes** [comment]
Thank you for this!  I will look through next week.

**Comment by RichardWagener365** [comment]
Hi - Richard @ Codethink

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by chamindra** [comment]
Hi 👋

**Comment by robbkeayes** [comment]
hi from Nomura

**Comment by amaltson** [comment]
Hello 👋

**Comment by katnovakovic** [comment]
Hi
