### ISSUE TITLE
27 FEB 2023 - InnerSource SIG License Working Group #6

### ISSUE THREAD

**Issue by chamindra** [finos/InnerSource#87]
## Date

_Monday_ 27 FEB 2023 - _11:00am_ EST / _4:00pm_ UK

## Untracked attendees

- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices

- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [ ] Convene & roll call (5mins)
- [ ] Display
      [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf)
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
       - Minutes: https://github.com/finos/InnerSource/issues/86
- [ ] Review discussion with Deutsche Bahn 
- [ ] Review improvements to questionnaire 
       - Questionnaire: https://forms.gle/tRAs8Aj6w6MWjgXC9)
- [ ] Review updates to the clauses.md
       - https://github.com/chamindra/InnerSource/blob/master/docs/licenses/clauses.md
- [ ] Plan for subsequent inner source project deep dives
- [ ] AOB, Q&A & Adjourn (5mins)

## Minutes
- We reviewed the last working group mintures and interview with Deutche Bahn
- We reviewed the questionnaire and input from Deutche Bahn and clauses.md
- We discussed how we can distribute the questionnaire to get more data point from more organizations
   - It was rasied that most Financial members would not permit access to a google questionnaire
   - It was requested to share a document version of the questionnaire to be distributed
   - FinOS (James) indicated that FinOS can play the role to securely mediate the questionnaire to the FinOS 
members and get the data points we need keeping mind of regulatory and security considerations of member organizations
      - However the questionnaire does not presently capture any organization details, through it would be good to enumberate it securely so that the data can be verified. GDPR and other clauses needed to be adhered if that were the case.
   - We also discussed reaching out to Inner Soruce commons to get more data points from other non-Financial institutions, especially those mentioned by Deutsche Bahn first
- We explored the the way the license generator would look using the Creative Common open source codebase
- An idea was raised that the machine readable version of the license could align to the ESBOM standards and there for add more value to tools that are working with ESBOM/EBOM 
- We are looking to recruit some developers to start working on the license generator, which is based on vue.js

## Action Items

- [ ] Prepare (word and ODF) versions of the questionnaire - Chamindra
- [ ] Work on mediating the questionnaire securely to other Financial institutions - James/FinOS/Chamindra
- [ ] Reachout to Creative Commons on distributing the questionnaire - Chamindra
- [ ] Recruit developers to help with the development of the license generator - FannieMae, Citi (Chamindra)

### Zoom Details

- https://zoom.us/j/94949043746?pwd=WnBFQjhpUnBjMWE0OUhqUGhhb0ZOdz09
- **Meeting ID:** 949 4904 3746
- **Passcode:** 067897

### Join by phone
Find your local number: https://zoom.us/u/adJnH9JOiY

### Mailing List

Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG
mailing list.

**Comment by chamindra** [comment]
👋

**Comment by mcleo-d** [comment]
Hello

**Comment by axarrafols** [comment]
Hello 👋

**Comment by mcleo-d** [comment]
Part of The Linux Foundation
SPDX SBOM Standard - https://spdx.dev/

**Comment by chamindra** [comment]
Licence generator example https://chooser-beta.creativecommons.org/
