### ISSUE TITLE
22 May 2023 - InnerSource SIG License Working Group Meeting Minutes

### ISSUE THREAD

**Issue by chamindra** [finos/InnerSource#94]
## Date

_Monday_ 22 May 2023 - _11:00am_ EST / _4:00pm_ UK

## Untracked attendees

- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices

- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [ ] Convene & roll call (5mins)
- [ ] Display
      [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf)
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Recap of OSR SIG meeting
- [ ] Inner Source Chooser License Tree
- [ ] Working session on code https://github.com/chamindra/finos-license-chooser
- [ ] AOB, Q&A & Adjourn (5mins)

## Minutes

- Chamindra gave an update on the progress of the InnerSource license generator
  - The original approach of using the creative commons model proved to be challenging to re-factor for purpose
  - Instead a python flask application was created by Chamindra that does the same thing. A demo was given of this generator
  - The license is constructed by different text clause options that can easily be modified independantly if required by the organization that uses it
 - It was discussed if the license generator could be hosted by FinOS
   - There was concern if any sensative material would then be contained 
   - However the way the application is constructed rightnow all input variables are only maintained in the browser session and no data is being stored. The final output is a downloadable MD file to the person desktop.
   - Peter mentioned that there is no binary signatures or data being maintained
   - James suggest we remove the FinOS term possibly if there is any liability, but it does need legal review. He was concerned if it is a email
     - However Chamindra mentioned that you would not email it, you would just downloaded it once it is generated
   - Chamindra also mentioned the code could also just be downloaded and be run in the organizations environment
   - James suggested that LF legal would need to take a look at it. They only need to look at the output
   - Chamindra mentioned that he still needs a legal review of the license clauses ideally from linux foundation 
     - James mentioned that the LF legal team might not be the best option
   - James mentioned that InnerSource commons would also be a legal review as they are the subject matter experts on the innersource licenses
- For now it was decided that we would only have the innersource part of the license generator and not the opensource license chooser
- Peter mentioned that the OSR survay was not an easy way
  - Collecting data from email would be a better way
- It was decided though it is still at a very early stage to get the license generator code published and have people improve it from there
- Chamindra said he might also need some help with the style sheet. Jo might be someone who can help

## Action Items

- [x] James to reach out to the LF legal team to see if they can review and get help with the clauses
- [x] Chamindra to reachout to Clare to see if they can provide some legal help
- [x] Chamindra to continue to work on the license generator code and publish it

### Zoom Details

- https://zoom.us/j/94949043746?pwd=WnBFQjhpUnBjMWE0OUhqUGhhb0ZOdz09
- **Meeting ID:** 949 4904 3746
- **Passcode:** 067897

### Join by phone
Find your local number: https://zoom.us/u/adJnH9JOiY

### Mailing List

Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG
mailing list.

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley 🏦

**Comment by mcleo-d** [comment]
James McLeod / FINOS

**Comment by chamindra** [comment]
👋  Hi Chamindra de Silva - Citi

**Comment by mcleo-d** [comment]
💸
